"""Initial migration

Revision ID: 5d766c71775b
Revises:
Create Date: 2024-08-28 20:20:05.231508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d766c71775b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'molecules',
        sa.Column('mol_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('smiles', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('mol_id'),
        sa.UniqueConstraint('smiles')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('molecules')
    # ### end Alembic commands ###
